/*
  Turns drizzle-kit's SQL output (./drizzle) into src/lib/db/migrations.gen.ts,
  so the app can migrate itself on start without reading files from disk
  (serverless bundles do not ship the ./drizzle folder).
  Run through `npm run db:generate`.
*/
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..");
const journal = JSON.parse(readFileSync(join(root, "drizzle/meta/_journal.json"), "utf8")) as {
  entries: { idx: number; tag: string }[];
};

const migrations = journal.entries
  .sort((a, b) => a.idx - b.idx)
  .map(({ tag }) => {
    const text = readFileSync(join(root, "drizzle", `${tag}.sql`), "utf8");
    const statements = text
      .split("--> statement-breakpoint")
      .map((s) => s.trim())
      .filter(Boolean);
    return { tag, statements };
  });

const out = `// Generated by scripts/bundle-migrations.ts. Do not edit; run \`npm run db:generate\`.
export const migrations: { tag: string; statements: string[] }[] = ${JSON.stringify(migrations, null, 2)};
`;
writeFileSync(join(root, "src/lib/db/migrations.gen.ts"), out);
console.log(`Bundled ${migrations.length} migration(s).`);
